### PR TITLE
Fix incorrect access to track fields on disc getters

### PR DESCRIPTION
**Pull request by cdown**

### CODE REVIEW

**Comment by cdown** [comment]
Tagging @pinkforest and @Serial-ATA -- am I missing something here or is this a bug?

Also any thoughts on #27 and #28?

Thanks, and sorry to bother!

**Comment by Serial-ATA** [comment]
You're not missing anything, I just don't have the ability to merge this. :smile:

**Comment by pinkforest** [comment]
Sorry I thought I had watch on.

**Comment by pinkforest** [comment]
Looks like we need to fix clippy - this will be a breaking change for 0.5 - @Serial-ATA any reason why we should not merge ?

**Comment by Serial-ATA** [comment]
Yeah, this is good to merge. The clippy fix is in #28

**Comment by cdown** [comment]
Thanks! Appreciate you both looking over the changes.

**Pull request merged**
